package ejulp.Vistas;

import ejulp.AccesoAdatos.AlumnoData;
import ejulp.AccesoAdatos.InscripcionData;
import ejulp.Entidades.Alumno;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import ejulp.AccesoAdatos.MateriaData;
import ejulp.Entidades.MateriaClass;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Nickemolmedo.
 */
public final class Inscripcion extends javax.swing.JInternalFrame {

    public DefaultComboBoxModel modeloComboAlumnos;

    /**
     * Creates new form Inscripcion
     */
    public Inscripcion() {
        initComponents();
        modeloComboAlumnos = new DefaultComboBoxModel<>(); // Crea el modelo de ComboBox
        combobox_ListarAlumnos.setModel(modeloComboAlumnos); // Asigna el modelo al JComboBox
        cargarCombo(); // Llena el modelo con datos
        construirTabla(); //Contrucimos el JTable.

        ButtonGroup AgruparBotones = new ButtonGroup();
        AgruparBotones.add(button_MateriasInscriptas);
        AgruparBotones.add(button_materiasNoIncriptas);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        combobox_ListarAlumnos = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        button_MateriasInscriptas = new javax.swing.JRadioButton();
        button_materiasNoIncriptas = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_materias = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        button_salir = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Formulario de Inscripcion");

        jLabel2.setText("Seleccione un Alumno:");

        combobox_ListarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox_ListarAlumnosActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Listado de Materias");

        button_MateriasInscriptas.setText("Materias Inscriptas");
        button_MateriasInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_MateriasInscriptasActionPerformed(evt);
            }
        });

        button_materiasNoIncriptas.setText("Materias no Inscriptas");
        button_materiasNoIncriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_materiasNoIncriptasActionPerformed(evt);
            }
        });

        tabla_materias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "AÑO"
            }
        ));
        jScrollPane1.setViewportView(tabla_materias);

        jButton1.setText("Inscribir");

        jButton2.setText("Anular Inscripcion");

        button_salir.setText("Salir");
        button_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31)
                        .addComponent(combobox_ListarAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button_MateriasInscriptas)
                                .addGap(157, 157, 157)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(button_materiasNoIncriptas)))
                        .addContainerGap(22, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(button_salir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(combobox_ListarAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_MateriasInscriptas)
                    .addComponent(button_materiasNoIncriptas)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_salir)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    AlumnoData alumnodata_temporal = new AlumnoData();

    InscripcionData inscripciondata_temporal = new InscripcionData();

    MateriaData materiadata_temporal = new MateriaData();

    public void cargarCombo() {

        ArrayList<Alumno> listadoAlumnos = alumnodata_temporal.listarAlumnos();

        // Limpia el modelo actual si es necesario
        modeloComboAlumnos.removeAllElements();

        // Agrega los objetos Alumno al modelo del ComboBox
        for (Alumno alumno : listadoAlumnos) {

            modeloComboAlumnos.addElement(alumno);

        }
    }

    public void construirTabla() {

        DefaultTableModel modelo_tabla = new DefaultTableModel(new String[]{"ID", "NOMBRE", "AÑO"}, materiadata_temporal.listarMaterias().size());

        tabla_materias.setModel(modelo_tabla);

    }


    private void combobox_ListarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_ListarAlumnosActionPerformed


    }//GEN-LAST:event_combobox_ListarAlumnosActionPerformed

    private void button_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_salirActionPerformed

        this.dispose();

    }//GEN-LAST:event_button_salirActionPerformed

    private void button_MateriasInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_MateriasInscriptasActionPerformed

        Alumno seleccionado = (Alumno) combobox_ListarAlumnos.getSelectedItem();

        Object[] datos_materia = new Object[3];

        ArrayList<MateriaClass> listadoMaterias = inscripciondata_temporal.obtenerMateriasCursadas(seleccionado.getIdAlumno());

        for (MateriaClass materias : listadoMaterias) {

            datos_materia[0] = materias.getIdMateria();
            datos_materia[1] = materias.getNombre();
            datos_materia[2] = materias.getAnioMateria();

        }


    }//GEN-LAST:event_button_MateriasInscriptasActionPerformed

    private void button_materiasNoIncriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_materiasNoIncriptasActionPerformed

        Alumno seleccionado = (Alumno) combobox_ListarAlumnos.getSelectedItem();

        Object[] datos_materia = new Object[3];

        ArrayList<MateriaClass> listadoMaterias = inscripciondata_temporal.obtenerMateriasNoCursadas(seleccionado.getIdAlumno());

        for (MateriaClass materias : listadoMaterias) {

            datos_materia[0] = materias.getIdMateria();
            datos_materia[1] = materias.getNombre();
            datos_materia[2] = materias.getAnioMateria();

        }


    }//GEN-LAST:event_button_materiasNoIncriptasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton button_MateriasInscriptas;
    private javax.swing.JRadioButton button_materiasNoIncriptas;
    private javax.swing.JButton button_salir;
    private javax.swing.JComboBox<String> combobox_ListarAlumnos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_materias;
    // End of variables declaration//GEN-END:variables
}
