package ejulp.Vistas;

import ejulp.AccesoAdatos.MateriaData;
import ejulp.Entidades.MateriaClass;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class Materia extends javax.swing.JInternalFrame {
private final MateriaData matData = new MateriaData();
private MateriaClass materiaActual = null;
    /**
     * Creates new form Materia
     */
    public Materia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botonBuscar = new javax.swing.JButton();
        codigo_materia = new javax.swing.JTextField();
        nombre_materia = new javax.swing.JTextField();
        jTaniomateria = new javax.swing.JTextField();
        jRadioButtonEstado = new javax.swing.JRadioButton();
        botonNuevo = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();

        setTitle("Materia");
        setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Materia");

        jLabel2.setText("Codigo");

        jLabel3.setText("Nombre");

        jLabel4.setText("Año");

        jLabel5.setText("Activo");

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        codigo_materia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigo_materiaActionPerformed(evt);
            }
        });

        nombre_materia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_materiaActionPerformed(evt);
            }
        });

        jTaniomateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTaniomateriaActionPerformed(evt);
            }
        });

        jRadioButtonEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEstadoActionPerformed(evt);
            }
        });

        botonNuevo.setText("Nuevo");
        botonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoActionPerformed(evt);
            }
        });

        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonNuevo)
                                .addGap(29, 29, 29)
                                .addComponent(botonEliminar)
                                .addGap(18, 18, 18)
                                .addComponent(botonGuardar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(codigo_materia, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(nombre_materia, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTaniomateria, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addComponent(botonSalir)
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonEstado)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonBuscar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(codigo_materia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nombre_materia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTaniomateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRadioButtonEstado))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonNuevo)
                    .addComponent(botonEliminar)
                    .addComponent(botonGuardar)
                    .addComponent(botonSalir))
                .addContainerGap(186, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    
    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {                                            
       try{
        Integer id = Integer.valueOf(codigo_materia.getText());
         materiaActual = matData.buscarMateria(id);
        if(materiaActual!=null){
            nombre_materia.setText(materiaActual.getNombre());
           String anioMateria = String.valueOf(materiaActual.getAnioMateria());
            jTaniomateria.setText(anioMateria);
            jRadioButtonEstado.setSelected(materiaActual.isActivo());
        }
       }catch(NumberFormatException ex){
           JOptionPane.showMessageDialog(this, "Debe ingresar un número valido");
       }
        //vista_Materia.buscarMateria(idMateria);
    }                                           

    
    
    private void nombre_materiaActionPerformed(java.awt.event.ActionEvent evt) {                                               
      
      //  nombre = textField_nombre.getText();
    }                                              

    private void codigo_materiaActionPerformed(java.awt.event.ActionEvent evt) {                                               
        
       //String num = codigo_materia.getText();
        if (isNumeric(codigo_materia.getText())) {

           // codigo_materia = Integer.parseInt(codigo_materia.getText());
           
  
       }
     
    }                                              

    private void jTaniomateriaActionPerformed(java.awt.event.ActionEvent evt) {                                              
        if (isNumeric(jTaniomateria.getText())){{
            
        }
    }                                             

    }    
    private void jRadioButtonEstadoActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        
        
       // activo = jRadioButtonEstado.isSelected();
    }                                                  

    private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        limpiarCampos();
        materiaActual=null;
    }                                          

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        try{
        Integer id = Integer.valueOf(codigo_materia.getText());
        String nombre = nombre_materia.getText();
        String anioMateria =jTaniomateria.getText();
        if(nombre.isEmpty()|| anioMateria.isEmpty()){
           JOptionPane.showMessageDialog(this, "No puede haber campos vacios"); 
           return;
        }
        
        Boolean estado = jRadioButtonEstado.isSelected();
        
        if(materiaActual==null){
            materiaActual = new MateriaClass(id,nombre,Integer.parseInt(anioMateria),estado);
            matData.guardarMateria(materiaActual);
            
        }else{
            materiaActual.setIdMateria(id);
            materiaActual.setNombre(nombre);
            materiaActual.setAnioMateria(Integer.parseInt(anioMateria));
            
            matData.modificarMateria(materiaActual);
        }
        
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(this, "Debe ingresar un id valido"); 
        }
        
    }                                            

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        
        if(materiaActual!=null){
        
        matData.eliminarMateria(materiaActual.getIdMateria());
        materiaActual=null;
        limpiarCampos();
    }else{
            JOptionPane.showMessageDialog(this, "NO hay materia eleccionada");
            }
        
    }                                             

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {                                           
        dispose();
    }                                          
     private void limpiarCampos(){
         codigo_materia.setText(" ");
         nombre_materia.setText(" ");
         jTaniomateria.setText(" ");
         jRadioButtonEstado.setSelected(true);
     }
    
     
     
      
    // Variables declaration - do not modify                     
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonNuevo;
    private javax.swing.JButton botonSalir;
    private javax.swing.JTextField codigo_materia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButtonEstado;
    private javax.swing.JTextField jTaniomateria;
    private javax.swing.JTextField nombre_materia;
    // End of variables declaration                   

    private boolean isNumeric(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
